#!/bin/csh -f

set statsrc = $1

# Get Experiments to plot
# -----------------------
set allexps = `cat $statsrc | grep DSC | grep -v \# | grep -v \*`
@   numexps = $#allexps / 2

   set DSC0 = `cat $statsrc | grep DSC0 | grep -v \#  | grep -v \* | cut -d: -f2`
   set EXPS = ''
   @   n = 2
while ($n <= $numexps )
   @   m = $n - 1
   set EXPS = "$EXPS `cat $statsrc | grep DSC$m | grep -v \#  | grep -v \* | cut -d: -f2`"
   @   n = $n + 1
end
set EXPS = `echo $EXPS`

echo DSC0: $DSC0
echo EXPS: $EXPS

set STATSDIR = corcmp
cd $STATSDIR

set files  = `/bin/ls -1 *_*_stats_*_*cmp_GLO_z_*.gif`

if( $#files >= 1 ) then

# Find Location of SEASON
# -----------------------
    @       n  = 0
    set  node  = ''
while( (.$node != '.corcmp') & (.$node != '.rmscmp') )
    @       n  = $n + 1
    set  node  = `echo $files[1] | cut -d_ -f$n`
end
    @       n  = $n + 3
   set SEASON = `echo $files[1] | cut -d_ -f$n | cut -d. -f1`



foreach VAR  ('corcmp' \
              'rmscmp' \
              'rmscmp_RANDOM'    \
              'rmscmp_BIAS'      \
              'rmscmp_AMPLITUDE' \
              'rmscmp_PHASE'     )

foreach EXP  ($EXPS)

     montage ${DSC0}_${EXP}_stats_hght_${VAR}_GLO_z* \
             ${DSC0}_${EXP}_stats_uwnd_${VAR}_GLO_z* \
             ${DSC0}_${EXP}_stats_vwnd_${VAR}_GLO_z* \
             ${DSC0}_${EXP}_stats_tmpu_${VAR}_GLO_z* \
             ${DSC0}_${EXP}_stats_sphu_${VAR}_GLO_z* \
             ${DSC0}_${EXP}_stats_hght_${VAR}_NHE_z* \
             ${DSC0}_${EXP}_stats_uwnd_${VAR}_NHE_z* \
             ${DSC0}_${EXP}_stats_vwnd_${VAR}_NHE_z* \
             ${DSC0}_${EXP}_stats_tmpu_${VAR}_NHE_z* \
             ${DSC0}_${EXP}_stats_sphu_${VAR}_NHE_z* \
             ${DSC0}_${EXP}_stats_hght_${VAR}_SHE_z* \
             ${DSC0}_${EXP}_stats_uwnd_${VAR}_SHE_z* \
             ${DSC0}_${EXP}_stats_vwnd_${VAR}_SHE_z* \
             ${DSC0}_${EXP}_stats_tmpu_${VAR}_SHE_z* \
             ${DSC0}_${EXP}_stats_sphu_${VAR}_SHE_z* \
             ${DSC0}_${EXP}_stats_hght_${VAR}_TRO_z* \
             ${DSC0}_${EXP}_stats_uwnd_${VAR}_TRO_z* \
             ${DSC0}_${EXP}_stats_vwnd_${VAR}_TRO_z* \
             ${DSC0}_${EXP}_stats_tmpu_${VAR}_TRO_z* \
             ${DSC0}_${EXP}_stats_sphu_${VAR}_TRO_z* \
        -tile 5x4 -geometry +0+0 ${DSC0}_${EXP}_${VAR}_${SEASON}_montage.gif & 

  foreach field ('hght' 'uwnd' 'vwnd' 'tmpu' 'sphu' )
     montage ${DSC0}_${EXP}_stats_${field}_${VAR}_SHE_z_${SEASON}.gif \
             ${DSC0}_${EXP}_stats_${field}_${VAR}_TRO_z_${SEASON}.gif \
             ${DSC0}_${EXP}_stats_${field}_${VAR}_NHE_z_${SEASON}.gif \
             ${DSC0}_${EXP}_stats_${field}_${VAR}_SPO_z_${SEASON}.gif \
             ${DSC0}_${EXP}_stats_${field}_${VAR}_XPO_z_${SEASON}.gif \
             ${DSC0}_${EXP}_stats_${field}_${VAR}_NPO_z_${SEASON}.gif \
        -tile 3x2 -geometry +0+0  ${DSC0}_${EXP}_${field}_${VAR}_${SEASON}_montage.gif &
  end

echo " "

end
end
wait
endif

