#!/usr/bin/env python3

import os, argparse, yaml

if __name__=='__main__':

    homdir_default=f'{os.environ["HOME"]}/geos5'
    datadir_default=homdir_default
    plotdir_default=f'{datadir_default}/plots_ocn'

    parser=argparse.ArgumentParser()
    parser.add_argument('expid', help='experiment ID')
    parser.add_argument('--homdir', 
                        default=homdir_default,
                        help='path to configs (gcm_run.j etc)')
    parser.add_argument('--datadir', 
                        default=datadir_default,
                        help='path to data output')
    parser.add_argument('--plotdir', 
                        default=plotdir_default,
                        help='path to plots output')
    parser.add_argument('--start_date', 
                        help='start date, yyyy-mm-dd')
    parser.add_argument('--end_date', 
                        help='end date, yyyy-mm-dd')
    args=parser.parse_args()

    conf=f'''# Auto generated by mkexp.py
expid:     {args.expid}
cmpexp:    []
data_path: {args.datadir}
plot_path: {args.plotdir}
dates:     [{args.start_date},{args.end_date}]
'''
    with open(f'{args.homdir}/{args.expid}/conf.yaml','w') as of:
        print(conf, file=of)

