version: 2.1

orbs:
  circleci-tools: geos-esm/circleci-tools@0.10.0

workflows:
  build-test:
    jobs:
      - build-GEOSgcm:
          name: build-GEOSgcm-on-<< matrix.compiler >>
          matrix:
            parameters:
              compiler: [gfortran, ifort]
          context:
            - docker-hub-creds

jobs:
  build-GEOSgcm:
    parameters:
      compiler:
        type: string
    executor:
      name: circleci-tools/<< parameters.compiler >>
      resource_class: large
    working_directory: /root/project
    steps:
      - run:
          name: "GMAO_Shared branch"
          command: echo ${CIRCLE_BRANCH}
      - circleci-tools/versions:
          compiler: << parameters.compiler >>
      - circleci-tools/checkout_fixture
      - circleci-tools/mepoclone
      - circleci-tools/mepodevelop
      - circleci-tools/checkout_if_exists
      - circleci-tools/cmake:
          compiler: << parameters.compiler >>
      - circleci-tools/buildinstall
      - circleci-tools/compress_artifacts
      - store_artifacts:
          path: /logfiles

