---

# Based on code from https://github.com/marketplace/actions/yaml-lint

name: Perl Critic

on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  perlcritic:
    runs-on: ubuntu-latest
    container:
      image: perl:latest

    steps:
      - uses: actions/checkout@v4
      - uses: gugod/action-perlcritic@fun
      - name: install perlnitpick
        run: cpanm --notest --quiet https://github.com/gugod/App-PerlNitpick.git
      - name: run perlnitpick
        run: perlnitpick --inplace --rules=RemoveTrailingWhitespace,RemoveUnusedVariables,RemoveUnusedInclude,RemoveUnusedImport .
      - name: suggester
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: perlnitpick
